/**
 * Converts array of chrome.cookies.Cookie objects to Netscape HTTP Cookie File format string.
 */
export function convertToNetscapeCookies(cookies) {
  let header = "# Netscape HTTP Cookie File\n";
  header += "# http://curl.haxx.se/rfc/cookie_spec.html\n";
  header += "# This file was generated by YouTube Downloader Extension\n\n";

  const lines = cookies.map(cookie => {
    const domain = cookie.domain;
    const includeSubdomains = domain.startsWith('.') ? "TRUE" : "FALSE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    // Expiration date in Unix epoch format. Default to 1 year in future if missing/session
    const expiration = cookie.expirationDate ? Math.floor(cookie.expirationDate) : Math.floor(Date.now() / 1000) + 31536000;
    const name = cookie.name;
    const value = cookie.value;

    return `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}`;
  });

  return header + lines.join("\n");
}
